### ISSUE TITLE
建议在go-cqhttp镜像打包时添加ffmpeg

### ISSUE THREAD

**Issue by yuantao313** [silicer/docker-build#1]
建议在go-cqhttp镜像打包时添加ffmpeg，以解决某些消息无法发送的问题

**Comment by silicer** [comment]
> 建议在go-cqhttp镜像打包时添加ffmpeg，以解决某些消息无法发送的问题

可以使用[namiya233/go-cqhttp](https://hub.docker.com/r/namiya233/go-cqhttp)
